<script setup lang="ts">
import { ref } from 'vue'
import AppIcon from '@/components/ui/AppIcon.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import BaseInput from '@/components/ui/BaseInput.vue'
import BaseSelect from '@/components/ui/BaseSelect.vue'
import BaseModal from '@/components/ui/BaseModal.vue'
import { useToastStore } from '@/stores/toast'
import { validate, RULES } from '@/composables/useValidation'

const toasts = useToastStore()

const form = ref({
  name: '',
  email: '',
  topic: 'Order support',
  message: '',
})

const errors = ref<Record<string, string>>({})
const modalOpen = ref(false)

const topics = [
  { label: 'Order support', value: 'Order support' },
  { label: 'Returns & exchanges', value: 'Returns & exchanges' },
  { label: 'Product & sizing', value: 'Product & sizing' },
  { label: 'Shipping', value: 'Shipping' },
  { label: 'Something else', value: 'Something else' },
]

/*
 * No Google Maps API key is required.
 *
 * This URL opens Google Maps and searches for your location.
 * Replace "Phnom Penh, Cambodia" with your exact store address later.
 */
const googleMapsUrl =
  'https://www.google.com/maps/search/?api=1&query=Phnom+Penh%2C+Cambodia'

/*
 * Google Maps Embed URL.
 *
 * This is an iframe embed, so you do NOT need a Google Maps API key.
 * Replace this with the iframe URL generated by:
 *
 * Google Maps → Share → Embed a map → Copy HTML
 */
const googleMapsEmbedUrl =
  'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.173!2d104.916!3d11.567!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3109517a4d8f5e01%3A0x4d8f5e01!2sPhnom+Penh%2C+Cambodia!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus'

const contactChannels = [
  {
    icon: 'map-pin',
    title: 'Address',
    body: 'Phnom Penh, Cambodia',
    href: googleMapsUrl,
    external: true,
  },
  {
    icon: 'phone',
    title: 'Phone',
    body: '+855 23 456 789',
    href: 'tel:+85523456789',
    external: false,
  },
  {
    icon: 'mail',
    title: 'Email',
    body: 'care@veste.com',
    href: 'mailto:care@veste.com',
    external: false,
  },
  {
    icon: 'clock',
    title: 'Opening Hours',
    body: 'Mon–Fri: 9am–8pm, Sat: 10am–6pm, Sun: Closed',
    href: '#business-hours',
    external: false,
  },
]

function submit() {
  const result = validate(
    {
      name: form.value.name,
      email: form.value.email,
      message: form.value.message,
    },
    {
      name: [RULES.required('Your name is required.')],
      email: [
        RULES.required('Email is required.'),
        RULES.email(),
      ],
      message: [
        RULES.required('Please tell us how we can help.'),
      ],
    },
  )

  errors.value = result.errors

  if (!result.valid) return

  modalOpen.value = true
}

function closeModal() {
  modalOpen.value = false

  form.value = {
    name: '',
    email: '',
    topic: 'Order support',
    message: '',
  }

  errors.value = {}

  toasts.success(
    'Message sent',
    'Our team will get back to you soon.',
  )
}
</script>

<template>
  <div>
    <!-- Hero -->
    <section class="bg-charcoal px-4 py-20 text-center text-bone">
      <p
        class="text-xs font-semibold uppercase tracking-[0.3em] text-gold"
      >
        Contact
      </p>

      <h1
        class="mx-auto mt-4 font-display text-4xl"
      >
        We'd love to hear from you
      </h1>

      <p
        class="mx-auto mt-3 max-w-md text-bone/70"
      >
        Questions, compliments, sizing SOS — our team replies fast,
        in plain English.
      </p>
    </section>

    <!-- Main Content -->
    <section class="px-4 py-16">
      <div
        class="wrap grid gap-8 lg:grid-cols-[1fr_1.1fr]"
      >
        <!-- Left Column -->
        <div class="space-y-6">
          <!-- Contact Channels -->
          <div class="grid gap-4 sm:grid-cols-2">
            <a
              v-for="c in contactChannels"
              :key="c.icon"
              :href="c.href"
              :target="c.external ? '_blank' : undefined"
              :rel="
                c.external
                  ? 'noopener noreferrer'
                  : undefined
              "
              class="flex items-start gap-4 rounded-3xl border border-charcoal/8 bg-white p-5 transition hover:shadow-lg hover:shadow-charcoal/5"
            >
              <span
                class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-beige/60 text-gold"
              >
                <AppIcon
                  :name="c.icon"
                  :size="19"
                />
              </span>

              <div class="min-w-0">
                <h3
                  class="font-semibold text-charcoal"
                >
                  {{ c.title }}
                </h3>

                <p
                  class="mt-0.5 text-sm font-medium text-gold"
                >
                  {{ c.body }}
                </p>
              </div>
            </a>
          </div>

          <!-- Business Hours -->
          <div
            id="business-hours"
            class="rounded-3xl bg-bone/50 p-6"
          >
            <h3
              class="flex items-center gap-2 font-display text-lg text-charcoal"
            >
              <AppIcon
                name="calendar"
                :size="18"
                class="text-gold"
              />

              Business Hours
            </h3>

            <div class="mt-4 space-y-3">
              <div
                v-for="h in [
                  {
                    day: 'Monday – Friday',
                    hours: '9:00 AM – 8:00 PM',
                  },
                  {
                    day: 'Saturday',
                    hours: '10:00 AM – 6:00 PM',
                  },
                  {
                    day: 'Sunday',
                    hours: 'Closed',
                  },
                ]"
                :key="h.day"
                class="flex items-center justify-between border-b border-charcoal/8 py-2 last:border-0 last:pb-0"
              >
                <span
                  class="text-sm text-charcoal/70"
                >
                  {{ h.day }}
                </span>

                <span
                  class="text-sm font-medium text-charcoal"
                  :class="
                    h.hours === 'Closed'
                      ? 'text-clay'
                      : ''
                  "
                >
                  {{ h.hours }}
                </span>
              </div>
            </div>
          </div>


        </div>

        <!-- Right Column -->
        <div class="space-y-6">
          <!-- Google Map -->
          <div
            class="contact-map-container overflow-hidden rounded-3xl border border-charcoal/8 bg-white"
          >
            <div class="relative aspect-video">
              <iframe 
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3908.8555405434154!2d104.88799181093744!3d11.562211988591006!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x310951adb4d4041d%3A0x8a90e729f62ad800!2sETEC%20Center!5e0!3m2!1skm!2skh!4v1789792115537!5m2!1skm!2skh" 
              width="600" height="450" style="border:0;" 
              loading="lazy" referrerpolicy="strict-origin-when-cross-origin">
            </iframe>
            </div>
          </div>

          <!-- Contact Form -->
          <form
            class="rounded-3xl border border-charcoal/8 bg-white p-7"
            @submit.prevent="submit"
          >
            <h2
              class="font-display text-xl text-charcoal"
            >
              Send a message
            </h2>

            <div class="mt-5 space-y-4">
              <!-- Name + Email -->
              <div
                class="grid gap-4 sm:grid-cols-2"
              >
                <BaseInput
                  v-model="form.name"
                  label="Your name"
                  :error="errors.name"
                  :required="true"
                />

                <BaseInput
                  v-model="form.email"
                  label="Email address"
                  type="email"
                  icon="mail"
                  :error="errors.email"
                  :required="true"
                />
              </div>

              <!-- Topic -->
              <BaseSelect
                v-model="form.topic"
                label="Topic"
                :options="topics"
              />

              <!-- Message -->
              <div class="flex flex-col gap-1.5">
                <label
                  class="text-sm font-medium text-charcoal"
                >
                  Message
                  <span class="text-clay">*</span>
                </label>

                <textarea
                  v-model="form.message"
                  rows="5"
                  class="w-full resize-none rounded-xl border px-4 py-3 text-sm text-charcoal transition-all duration-200 focus:outline-none"
                  :class="
                    errors.message
                      ? 'border-clay focus:border-clay focus:ring-2 focus:ring-clay/20'
                      : 'border-charcoal/15 hover:border-charcoal/30 focus:border-charcoal focus:ring-2 focus:ring-charcoal/10'
                  "
                  :aria-invalid="
                    Boolean(errors.message)
                  "
                  placeholder="How can we help?"
                />

                <p
                  v-if="errors.message"
                  class="text-xs font-medium text-clay"
                >
                  {{ errors.message }}
                </p>
              </div>

              <!-- Submit -->
              <BaseButton
                type="submit"
                size="lg"
                block
              >
                <AppIcon
                  name="send"
                  :size="16"
                />

                Send message
              </BaseButton>
            </div>
          </form>
        </div>
      </div>
    </section>

    <!-- Success Modal -->
    <BaseModal
      :open="modalOpen"
      title="Message sent"
      subtitle="Thanks for reaching out."
      size="sm"
      @close="closeModal"
    >
      <p
        class="text-sm leading-relaxed text-charcoal/65"
      >
        We've received your message about
        <span class="font-semibold text-charcoal">
          {{ form.topic }}
        </span>.

        A member of our team will reply to
        <span class="font-semibold text-charcoal">
          {{ form.email }}
        </span>
        within 24 hours.
      </p>

      <BaseButton
        class="mt-6 w-full"
        @click="closeModal"
      >
        Done
      </BaseButton>
    </BaseModal>
  </div>
</template>

<style scoped>
.contact-map-container {
  min-height: 300px;
}

@media (max-width: 768px) {
  .contact-map-container {
    min-height: 240px;
  }
}
</style>
